src/ES/MessengerBundle/Entity/MessaggioBase.php
<?php

namespace ES\MessengerBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * ES\MessengerBundle\Entity\MessaggioBase
 *
 * @ORM\Table(name="msg_base")
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({
 *          "rdo_cer"                       = "ES\MessengerBundle\Entity\RDO\Cer", 
 *          "rdo_mps"                       = "ES\MessengerBundle\Entity\RDO\Mps", 
 *          "rdo_servizi"                   = "ES\MessengerBundle\Entity\RDO\Servizi", 
 *          "rdi"                           = "ES\MessengerBundle\Entity\Messaggio", 
 *          "risposta"                      = "ES\MessengerBundle\Entity\Risposta", 
 *          "system"                        = "ES\MessengerBundle\Entity\Sistema", 
 *          "null"                          = "MessaggioBase" 
 * })
 * @ORM\HasLifecycleCallbacks
 * @ORM\Entity(repositoryClass="ES\MessengerBundle\Entity\MessaggioBaseRepository")
 */
abstract class MessaggioBase {

    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var Doctrine\Common\Collections\ArrayCollection $destinatari
     * 
     * @ORM\OneToMany(targetEntity="Destinatario", mappedBy="messaggio", cascade={"persist", "remove", "merge", "refresh"})
     */
    private $destinatari;

    /**
     * @var ES\UserBundle\Entity\User $utente
     * 
     * @ORM\ManyToOne(targetEntity="ES\UserBundle\Entity\User")
     * @ORM\JoinColumn(name="from_utente_id", referencedColumnName="id", nullable=true)
     */
    private $from_utente;
    
    

    /**
     * @var string $from_nome
     *
     * @ORM\Column(name="from_nome", type="string", length=64, nullable=true)
     */
    private $from_nome;

    /**
     * @var string $from_cognome
     *
     * @ORM\Column(name="from_cognome", type="string", length=64, nullable=true)
     */
    private $from_cognome;

    /**
     * @var string $from_azienda
     *
     * @ORM\Column(name="from_azienda", type="string", length=128, nullable=true)
     */
    private $from_azienda;

    /**
     * @var string $from_email
     *
     * @ORM\Column(name="from_email", type="string", length=128)
     */
    private $from_email;

    /**
     * @var string $subject
     *
     * @ORM\Column(name="subject", type="string", length=255)
     */
    private $subject;

    /**
     * @var text $testo
     *
     * @ORM\Column(name="testo", type="text", nullable=true)
     */
    private $testo;

    /**
     * var string $pre_slug 
     * 
     * @ORM\Column(name="pre_slug", type="string", length=255)
     */
    private $pre_slug;

    /**
     * var string $tipologia
     * 
     * @ORM\Column(name="tipologia", type="string", length=16)
     */
    private $tipologia;

    /**
     * var string $slug 
     * 
     * @Gedmo\Slug(fields={"pre_slug"})
     * @ORM\Column(name="slug", type="string", length=255, unique=true)
     */
    private $slug;

    /**
     * @var datetime $created_at
     *
     * @ORM\Column(name="created_at", type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @var datetime $updated_at
     *
     * @ORM\Column(name="updated_at", type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @var \octrine\Common\Collections\ArrayCollection $allegati
     * 
     * @ORM\OneToMany(targetEntity="Allegato", mappedBy="messaggio", cascade={"persist", "remove", "merge", "refresh"})
     */
    private $allegati;

    /**
     * @var \octrine\Common\Collections\ArrayCollection $allegati
     * 
     * @ORM\OneToMany(targetEntity="Allegato", mappedBy="conversazione", cascade={"persist", "remove", "merge", "refresh"})
     */
    private $allegati_conversazione;

    /**
     * @ORM\OneToMany(targetEntity="Risposta", mappedBy="messaggio", cascade={"persist", "remove", "merge", "refresh"})     
     * @ORM\OrderBy({"created_at" = "ASC"}) 
     */
    private $risposte;

    function __construct() {
        $this->risposte = new \Doctrine\Common\Collections\ArrayCollection();
        $this->destinatari = new \Doctrine\Common\Collections\ArrayCollection();
        $this->allegati = new \Doctrine\Common\Collections\ArrayCollection();
        $this->allegati_conversazione = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set destinatari
     *
     * @param \Doctrine\Common\Collections\ArrayCollection  $destinatari
     */
    public function setDestinatari($destinatari) {
        $this->destinatari = $destinatari;
    }

    /**
     * Get destinatari
     *
     * @return \Doctrine\Common\Collections\ArrayCollection  
     */
    public function getDestinatari() {
        return $this->destinatari;
    }

    /**
     * Get destinatari
     *
     * @return integer 
     */
    public function addDestinatari($destinatari) {
        $this->destinatari->add($destinatari);
    }

    /**
     * Set destinatari
     *
     * @param \Doctrine\Common\Collections\ArrayCollection  $allegati
     */
    public function setAllegati($allegati) {
        $this->allegati = $allegati;
    }

    /**
     * Get destinatari
     *
     * @return \Doctrine\Common\Collections\ArrayCollection 
     */
    public function getAllegati() {
        return $this->allegati;
    }

    /**
     * Get destinatari
     *
     * @return integer 
     */
    public function addAllegati($allegati) {
        $this->allegati->add($allegati);
    }

    /**
     * Set destinatari
     *
     * @param \Doctrine\Common\Collections\ArrayCollection  $allegati
     */
    public function setAllegatiConversazione($allegati) {
        $this->allegati_conversazione = $allegati;
    }

    /**
     * Get destinatari
     *
     * @return \Doctrine\Common\Collections\ArrayCollection 
     */
    public function getAllegatiConversazione() {
        return $this->allegati_conversazione;
    }

    /**
     * Get destinatari
     *
     * @return integer 
     */
    public function addAllegatiConversazione($allegati) {
        $this->allegati_conversazione->add($allegati);
    }
    
    
     

    /**
     * Set from_user_id
     *
     * @param \ES\UserBundle\Entity\User $from_utente
     */
    public function setFromUtente(\ES\UserBundle\Entity\User $from_utente, $set_id = false) {
        $this->from_utente = $set_id ? $from_utente->getId() : $from_utente;
        $destinatario = new Destinatario();
        $destinatario->setDestinatario($from_utente);
        $destinatario->setMessaggio($this);
        $destinatario->setConversazione($this->getConversazione());
        $destinatario->setNotificato(true);
        $destinatario->setLetto(true);
        $this->addDestinatari($destinatario);
        $this->setFromNome($from_utente->getFirstname());
        $this->setFromCognome($from_utente->getLastname());
        $this->setFromEmail($from_utente->getShowroom() ? $from_utente->getShowroom()->getEmail() : '');
        $this->setFromAzienda($from_utente->getShowroom() ? $from_utente->getShowroom()->getRagioneSociale() : '');
    }

    /**
     * Get from_user_id
     *
     * @return \ES\UserBundle\Entity\User 
     */
    public function getFromUtente() {
        return $this->from_utente;
    }

    /**
     * Set from_nome
     *
     * @param string $fromNome
     */
    public function setFromNome($fromNome) {
        $this->from_nome = $fromNome;
    }

    /**
     * Get from_nome
     *
     * @return string 
     */
    public function getFromNome() {
        return $this->from_nome;
    }

    /**
     * Set from_cognome
     *
     * @param string $fromCognome
     */
    public function setFromCognome($fromCognome) {
        $this->from_cognome = $fromCognome;
    }

    /**
     * Get from_cognome
     *
     * @return string 
     */
    public function getFromCognome() {
        return $this->from_cognome;
    }

    /**
     * Set from_azienda
     *
     * @param string $fromAzienda
     */
    public function setFromAzienda($fromAzienda) {
        $this->from_azienda = $fromAzienda;
    }

    /**
     * Get from_azienda
     *
     * @return string 
     */
    public function getFromAzienda() {
        return $this->from_azienda;
    }

    /**
     * Set from_email
     *
     * @param string $fromEmail
     */
    public function setFromEmail($fromEmail) {
        $this->from_email = $fromEmail;
    }

    /**
     * Get from_email
     *
     * @return string 
     */
    public function getFromEmail() {
        return $this->from_email;
    }

    /**
     * Set subject
     *
     * @param string $subject
     */
    public function setSubject($subject) {
        $this->subject = $subject;
    }

    /**
     * Get subject
     *
     * @return string 
     */
    public function getSubject() {
        return $this->subject;
    }

    /**
     * Set testo
     *
     * @param text $testo
     */
    public function setTesto($testo) {
        $this->testo = $testo;
    }

    /**
     * Get testo
     *
     * @return text 
     */
    public function getTesto() {
        return $this->testo;
    }

    /**
     * get risposte
     *
     * @return \Doctrine\Common\Collections\ArrayCollection 
     */
    public function getRisposte() {
        return $this->risposte;
    }

    /**
     * ser risposte
     *

src/ES/MessengerBundle/Resources/views/Messenger/moduli/centroMessaggi.html.twig
<h4>Messenger - <a href="javascript:init_tipo(),init_filtri(),show(['servizi','mps','cer','rdi','post','system']),aggiornaTestoFiltro(0)">Tutti</a></h4>
<div class="clearer ten"></div>
<ul class="filters-mailing">
    {% set indice = 1 %}
    {% for categoria in categorie_messaggi %}
        <li {% if not categoria.sottocategorie %}class="hover"{% endif %}><a id="testo{{ indice }}" href="javascript:init_tipo(),init_filtri(),show({{ categoria.show }}),aggiornaTestoFiltro({{ indice }})" class="rdo-center">{{ categoria.label|raw }} <span class="counter rounded-3 shadow">{{ categoria.nuovi }}/{{ categoria.numero }}</span></a>
            {% set indice = indice + 1 %}
            {% if categoria.sottocategorie %}
                <ul class="submenu">
                    {% for sottocategoria in categoria.sottocategorie %}
                        <li class="hover"><a id="testo{{ indice }}" href="javascript: javascript:init_tipo(),init_filtri(),show({{ sottocategoria.show }}),aggiornaTestoFiltro({{ indice }})">{{ sottocategoria.label|raw }} <span class="counter rounded-3 shadow">{{ sottocategoria.nuovi }}/{{ sottocategoria.numero }}</span></a></li>
                        {% set indice = indice + 1 %}
                    {% endfor %}
                        <!-- BETA 0.1 BLANKATO
                        {#{% if rdo_rimasti == 0 and rdo_rimasti is not null%}
                        <li class="hover"><a href="#">Acquista <strong>RDO</strong><span class="counter rounded-3 shadow"></span></a></li>
                        {% else %}
                        <li class="hover"><a href="javascript: javascript:init_tipo(),init_filtri(),show(['rdo'])">Richiesta <strong>RDO</strong><span class="counter rounded-3 shadow">{{rdo_rimasti}}</span></a></li>                        
                        {% endif %} #}
                        -->
                    </ul>
            {% endif %}
                </li>
    {% endfor %}
            </ul>

src/ES/MessengerBundle/Resources/views/Messenger/moduli/dashboard.html.twig
<script type="text/javascript">
    var url_add_cerchia = '{{ path('rubrica_add_cercio') }}';
    var cerchie = [];
    var colleghi = [];
    {% for cer in cerchie %}
        {% if not cer.predefinito %}
            cerchie.add({id: '{{cer.id}}', label: '{{cer.cerchia}}'})
        {% else %}
            {% for utente in cer.contatti %}
                colleghi.add({{utente.contatto.id}});
            {% endfor %}
        {% endif %}
    {% endfor %}
</script>
<article class="dashboard-box clearfix">
    <div id="centro_messaggi"  class="new-email">
        {% include 'EcoSeekrMessengerBundle:Messenger:moduli/centroMessaggi.html.twig'%}
    </div>
    <div class="clearer twenty"></div>
    <div id="rubrica">
        {% include 'EcoSeekrMessengerBundle:Messenger:moduli/rubrica.html.twig'%}
        {#% include 'EcoSeekrMessengerBundle:Messenger:moduli/strumenti.html.twig'%#}
    </div>
</article>

src/ES/MessengerBundle/Resources/views/Messenger/moduli/filtri.html.twig
<section id="title_dashboard" class="clearfix margin-top-5 gradient-lightmedium" style="min-height: 40px;">
    <section class="margin-left-10 margin-right-10">
        <section class="colsx-filter">
            <ul class="button-dark" style="position: absolute; top: -16px; left: 0;">
                <li class="blue first last msg_button" id="nuovo_messaggio"><span><a href="javascript:nuovaDiscussione()">+ Nuovo messaggio</a></span></li>
                <li class="blue first last msg_button" style="display: none;" id="listing_messaggi"><span><a href="javascript:aggiorna()">< Torna ai Messaggi</a></span></li>
            </ul>
        </section>
        <section class="coldx-listing">
            <p style="position: absolute; top: -6px; left: 0;" class="search-mess-filter" id="select_filter"><span>filtra <b id="tipo-messaggi"></b> per...</span></p>
            <div class="clearer"></div>
            <section style="position: relative; top: 23px; left: 3px;">
                <section id="list_filter" class="clearfix box-light shadow-strong search-mess-filter-listing no-display">
                    <ul class="menu-tools message-filter">
                        {% for filtro in filtro_tendina%}
                        <li class="filtro-tendina {% if loop.last %} last shadow{% endif %}" tipo='{{filtro.tipo|raw}}' filtri="{{filtro.filtro|raw}}"><a href="javascript:void(0)">{{filtro.label|raw}}</a></li>
                        {% endfor%}
                    </ul>
                </section>
            </section>
            <form style="position: absolute; top: -6px; right: 0px;" onsubmit="return false;">
                <section class="search-mess-area">
                    <input type="text" id="ricerca_messaggi" class="placeholder" name="" value="" placeholder="Cerca tra i messaggi, le comunicazioni e le email">
                    <div class="clearer"></div>
                </section>
            </form>
        </section>
    </section>
</section>

src/ES/MessengerBundle/Resources/views/Messenger/moduli/intestazione.html.twig
{% set utente = app.session.get('user') %}
<section id="header-tab" class="no-padding relative">
    <div class="fixed-width clearfix margin-top-20 margin-bottom-10">
        <h2 class="text-shadow normal">Centro Comununicazioni</h2>
        <h4 class="text-shadow normal">Messenger</h4>
        {% include "EcoSeekrNuvolaBundle:Nuvola:commons/shortcut.html.twig" %}
    </div>
</section>

src/ES/MessengerBundle/Resources/views/Messenger/moduli/risultati.html.twig
<section class="coldx-listing" id="messager-list">
    <article class="clearfix " >
        <ul class="listing-result">
            {% include 'EcoSeekrMessengerBundle:Messenger:moduli/risultatiAjax.html.twig' %}
        </ul>
    </article>
    {% if risultati_totali is defined%}
        {% if risultati_totali > 10 %}
            <div id="more-result-container">
                <div class="centered" style="display: block; width: 300px;"><button class="button-orange big margin-top-10" style="width: 100%;" onclick="scrollResult()" id="more-result">Visualizza più risultati</button></div>
            </div>
        {%endif%}
    {%endif%}
</section>

src/ES/MessengerBundle/Resources/views/Messenger/moduli/risultatiAjax.html.twig
{#risultati_totali è quando arrivo dai filtri, result è quando arrivo dalla rubrica#}
{% if risultati_totali is defined%}
    {% if risultati_totali > 0 %}
        {% if risultati_totali == 1%}
            <li id="sezione" class="mid-light-grey"><span class="padding-left-15">E' stato trovato <strong>{{risultati_totali}}</strong> risultato</span></li> 
        {% else %}
            <li id="sezione" class="mid-light-grey"><span class="padding-left-15">Sono Stati trovati <strong>{{risultati_totali}}</strong> risultati</span></li>    
        {% endif %}
    {% else %}
        <li>
        {# <h2 style="text-align: left;">La Casella di posta è vuota.</h2>#}
            <h2 style="text-align: left;">Non sono presenti messaggi <span id="context"></span>.</h2>
            <div class="clearer ten"></div>
        </li> 
    {% endif %}
    {% for id, result in results %}   
       {% include 'EcoSeekrMessengerBundle:Messenger:moduli/risultato.html.twig' %}
    {% endfor %}    
{% elseif  risultati_totali is not defined and results is defined%}
   {% if results|length > 0 %}
        {% if results|length == 1%}
             <li id="sezione" class="mid-light-grey"><span class="padding-left-15">E' stato trovato <strong>{{results|length}}</strong> risultato</span></li>
        {%else%}
             <li id="sezione" class="mid-light-grey"><span class="padding-left-15">Sono Stati trovati <strong>{{results|length}}</strong> risultati</span></li>
        {% endif %}
   {% else %}
        <li>
            <h2 style="text-align: left;">Non sono presenti messaggi <span id="context"></span>.</h2>
            <div class="clearer ten"></div>
        </li> 
    {% endif %}
    {% for id, result in results %}   
       {% include 'EcoSeekrMessengerBundle:Messenger:moduli/risultato.html.twig' %}
    {% endfor %}    
{% endif %}    

src/ES/MessengerBundle/Resources/views/Messenger/moduli/risultatiScrollAjax.html.twig
{% for id, result in results %}
    {% include 'EcoSeekrMessengerBundle:Messenger:moduli/risultato.html.twig' %}
{% endfor %}

src/ES/MessengerBundle/Resources/views/Messenger/moduli/risultato.html.twig
<li class='discussione clearfix {% if not result.messaggioLetto %}da-leggere{% endif %}' id="d_{{result.slug}}">
    <section class="col-desc col-desc-mess left clearfix">
        <div class="img_thumb_listing margin-right-10 relative goto_discussione hover" id="{{result.slug}}">
            {% if result.fromUtente.professionista %}
                <div class="flag premium tiptip" title="Utente Premium Plus">Premium</div>                
            {% endif %}
            <a href="javascript:void(0)">
                {% if result.isLock <= 0 %}
                    {% include 'EcoSeekrProfessionistaBundle::avatar.html.twig' with {'utente': result.lastMittenteUserSerialize, 'size': 50} %}
                {% else %}
                    <div style="width: 50px; height: 50px;">
                        <img class="rounded-3" style="margin: 0px 0px;" src="/images/user_no_placeholder.jpg" height="50" width="50">
                    </div>
                {% endif%}        
            </a>
        </div>
        <article class="mess-body left relative">
            {% if  result.isLock <= 0 %}
               {% if result.fromUtente.professionista %}
                   {#<div class="flag premium tiptip" title="Utente Premium Plus">Premium</div>#}
               {% endif %}   
            {% else %}
               <button onclick="window.location('{{ path('pay_rdo') }}')">Acquista RDO</button>    
            {% endif %}
            <h3 class="text-lightblue normal goto_discussione hover {{ result.tipo }} padding-left-15 " style="font-size: 14px;" id="{{result.slug}}" alt="{{ result.subject }}" title="{{ result.subject }}">
                {% if result.risposte|length > 0 %} 
                    
                {% endif %}
                {% if result.isLock <= 0 %}
                    {{ result.subject|truncate(75) }}
                {% endif %}
            </h3>
            <p class="padding-left-15 text-gray">
                {% if  result.isLock <= 0 %}
                    <span class="relative" >
                        <span class="goto_discussione hover tiptip" id="{{result.slug}}" alt="{{ result.nomiUtenti.big }}" title="{{ result.nomiUtenti.big }}">
                            {{ result.nomiUtenti.small }}
                        </span>
                        {% if result.isLock <= 0 and result.tipo != 'system' %}
                            <span class="absolute rubrica_{{ result.fromUtente.id }} hover" style="font-size: 0; line-height: 0; top: 8px; right: -15px;">
                                <span class="add-rubrica tiptip add" style="background-position: -1514px -1417px;" title="Aggiungi a rubrica" rel="{{result.fromUtente.id}}"></span>
                            </span>
                            {#<ul class="item-tools button-light only-icon on-show rubrica_{{ result.fromUtente.id }}" style="top: -2px; right: 15px;">
                                <li class="smaller first last"><a href="javascript:void(0)" class="add-rubrica tiptip" title="Aggiungi a rubrica" rel="{{result.fromUtente.id}}"><span class="add">Aggiungi alla rubrica</span></a></li>
                            </ul>#}
                        {% endif %}  
                    </span>
                {% else %}
                    <span class="relative" >
                        <span class="goto_discussione" id="{{result.slug}}" alt="{{ result.nomiUtenti.big }}" title="{{ result.nomiUtenti.big }}">
                            {{result.fromUtente.tipoMittente}}
                        </span>
                        {% if result.isLock <= 0 and result.tipo != 'system' %}
                            <span class="absolute rubrica_{{ result.fromUtente.id }} hover" style="font-size: 0; line-height: 0; top: -8px; right: -15px;">
                                <span class="add-rubrica tiptip add" style="background-position: -1514px -1417px;" title="Aggiungi a rubrica" rel="{{result.fromUtente.id}}"></span>
                            </span>
                            {#<ul class="item-tools button-light only-icon on-show rubrica_{{ result.fromUtente.id }}" style="top: -2px; right: 15px;">
                                <li class="smaller first last"><a href="javascript:void(0)" class="add-rubrica tiptip" title="Aggiungi a rubrica" rel="{{result.fromUtente.id}}"><span class="add">Aggiungi alla rubrica</span></a></li>
                            </ul>#}
                        {% endif %}  
                    </span>
                {% endif %}
            </p>
            
            {% if  result.isLock <= 0 %}
                {% if result.risposte|length > 0 %}
                    <p class="text-grey goto_discussione hover {% if result.lastMittenteId == app.session.get('user').id %}reply-out{% else %}reply-in{% endif %} margin-left-15 padding-left-15" id="{{result.slug}}">{{ result.risposte|length }} {% if result.risposte|length > 1 %}risposte{% else %}risposta{% endif %} - Ultima risposta inviata da {% if result.lastMittenteId == app.session.get('user').id %}te{% else %}{{result.lastMittente}}{% endif %}:<br><i>"{{ result.lastAnteprima }}"</i></p>
                {% endif %}
            {% endif %}
        </article>
    </section>
    <section class="col-info col-info-mess right">
        <span class="date-stamp right" time="{{ result.lastMessageAt|date("Y-m-d H:i:s") }}"></span>
        <div class="clearer five"></div>
        
        {% if result.messaggioLetto %}
            <a href="javascript: void(0)" class="readstate readstate-mess right tiptip" letto="s" title="Segna come da leggere">Segna come da leggere</a>
        {% else %}
            <a href="javascript: void(0)" class="readstate readstate-ok-mess right tiptip" letto="n" title="Segna come letto">Segna come letto</a>
        {% endif %}
            
        {% if result.allegati|length > 0 %} 
            <a href="javascript: void(0)" class="attachment-small right tiptip no-hover" title="Sono presenti dei file allegati"></a>
        {% endif %}
            
        {% if not result.fromUtente.emailVerificata%}
            <a href="javascript: void(0)"  class="not-verified right tiptip no-hover" title="Utente non verificato">Utente non verificato</a>
        {% endif %}
            
        <div class="clearer"></div>
        
        {% if result.messaggioSpam%}
            <a href="javascript: void(0)" class="spamstate no-spam-mess right tiptip" title="Rimuovi dallo Spam">Rimuovi dallo Spam</a>
        {% else %}
            <a href="javascript: void(0)" class="spamstate spam-mess right tiptip" title="Segna come Spam">Segna come Spam</a>
        {% endif %}
            
        {% if result.messaggioLetto %}
            {% if result.messaggioArchiviato%} {# Cambiare icona quando il messaggio è archiviato #}
                <a href="javascript: void(0)" id ="archivia" class="storestate store-mess right tiptip" title="Recupera messaggio">Recupera messaggio</a>
            {% else %}
                <a href="javascript: void(0)" id ="archivia" class="storestate recover-mess right tiptip" title="Archivia messaggio">Archivia messaggio</a>
            {% endif %}
        {% else %}
            <a href="javascript: void(0)" id ="archivia" class="storestate recover-mess no-display right tiptip" style="display:none"title="Archivia messaggio">Archivia messaggio</a>
        {%endif%}
    </section>
</li>

src/ES/MessengerBundle/Resources/views/Messenger/moduli/rubrica.html.twig
{% set preferiti = 0 %}
{% for categoria,contatti in rubrica%}
    {% if categoria != 'numero_contatti' and categoria != 'contatti_in_rubrica' %}
        {% set preferiti = preferiti + contatti|length %}
    {% endif %}
{% endfor %}
{#<h4>Preferiti - <a href="javascript:void(0);" id="aggiungi_rubrica">Aggiungi</a></h4>#}
<section class="baloon-container no-display" id="invito_rubrica_baloon"> 
    <div class="arrow-up a-right" id="arrow-up"></div>
    <section class="box-float bacheca shadow-strong clearfix" >
        {% include 'EcoSeekrMessengerBundle:Rubrica:formInvito.html.twig' %}
    </section>
</section>  
<div class="clearer ten"></div>
<div class="box-light padding-3 rounded-3 gradient-light ">
    <h4 class="favourites hover text-lightblue padding-left-20" onclick="baloon_preferiti();">Preferiti <span class="counter rounded-3 shadow">{{ preferiti }}</span></h4>
    <section class="baloon-container no-display" id="favoriti_baloon" style="left: -15px;"> 
        <div class="arrow-up a-right" id="arrow-up"></div>
        <section class="box-float bacheca shadow-strong clearfix no-padding" >
            <div class="close-box-main hover shadow rounded-10" id="baloon-favoriti-close">Chiudi</div>
            {% if rubrica.numero_contatti > 0 %}
                {% for categoria,contatti in rubrica%}
                    {% if categoria != 'numero_contatti' and categoria != 'contatti_in_rubrica' %}
                        <ul class="filters-mailing">
                            {% for contatto in contatti %}
                                {% if loop.length < 20 %}
                                    <li class="contatto hover clearfix relative padding-10 no-margin" id="ru_{{contatto.id}}">
                                        <a class="{{ categoria }} left margin-right-50" href="javascript: loadContent(ru_contact_tools+'?contatto={{contatto.id}}', ru_target, '#baloon-contact-tools', false);setPositionBallon('baloon-contact-tools', 'ru_{{contatto.id}}')">
                                            <span id="cn_{{contatto.id}}">{{contatto.label}}</span>
                                                {% if contatto.tipo == 'showroom' %}
                                                    <br><small>{{ contatto.nome }}</small>
                                                {% else %}
                                                    {% if contatto.azienda %}<br><small>{{ contatto.azienda }}</small>{% endif %}
                                                {% endif %}
                                        </a>
                                        <span class="op">
                                            <a href="javascript: tuttiMessaggi({{contatto.id}})" class="user-mess left" title="Messaggi">Messaggi</a>
                                            <a href="javascript: nuovoMessaggio({{contatto.id}})" class="new-mess left" title="Nuovo messaggio">Nuovo messaggio</a>
                                            <a href="javascript: eliminaRubrica({{contatto.id}})" id="delete_{{contatto.id}}" class="delete-item left" title="Cancella il contatto">Elimina Contatto</a>
                                        </span>
                                        <div class="baloon-container no-display" id="baloon-contact-tools" style="left:0;">
                                            <div class="arrow-up a-right" id="arrow-up"></div>
                                            <section class="box-float bacheca shadow-strong clearfix" >
                                            </section>
                                        </div>    
                                    </li>
                                    {% if not loop.last %}
                                        <div class="clearer"></div>
                                        <div class="hr-light"></div>
                                        <div class="clearer"></div>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                        </ul>
                    {% endif %}
                {% endfor %}
            {% else %}
        </section>
    </section>
</div>
<p class="note">Nessun contatto in rubrica</p>
{% endif %}

src/ES/MessengerBundle/Resources/views/Messenger/moduli/strumenti.html.twig
<h4>I tuoi dati</h4>

<div class="clearer ten"></div>
<ul class="menu-tools">
    <li><a href="#" class="tiptip" title="Esci">Modifica il tuo profilo <small>(in costruzione)</small></a></li>
    <li><a href="{{ path('logout') }}" class="tiptip" title="Scollegati dal sistema">Esci</a></li>
    <li class="gradient-red"><a class="feedback no-background" href="mailto:feedback@ecoseekr.com?subject=Segnalazione di errore o miglioramento da feedback Ecoseekr">Consiglio o errore? ...scrivici</a></li>
</ul>